name: CRA Frontend CI/CD

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
          cache: npm

      - name: Clean and force install AJV 8
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install ajv@8.12.0 ajv-keywords@5.1.0 --save-dev --legacy-peer-deps --no-audit
          npm install schema-utils@4.2.0 --save-dev --legacy-peer-deps --no-audit
          npm install --legacy-peer-deps --no-audit --force
          echo "=== Проверка версий ==="
          npm list ajv ajv-keywords schema-utils

      - name: Build React app
        run: npm run build
        env:
          CI: false
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload build to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          key_base64: true
          port: ${{ secrets.SSH_PORT }}
          source: "build/*"
          target: "/var/www/buildGM"
          strip_components: 1

      - name: Reload nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          key_base64: true
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo -n systemctl reload nginx
